bind:
  host: 0.0.0.0
  port: 7000

# Understand how to hide env variables
db:
  type: mysql
  url: mysql+pymysql://root:1234567@0.0.0.0:3306/mock_api
  engine: 
    pool_size: 100
    max_overflow: 0 

auth:
  secret-key: 'abc'

app:
  debug: True
  name: QAStart
  default_locale: ru-RU
  base_url: http://127.0.0.1:7000/
  # default_locale: en-EN
