"""Add user fields

Revision ID: 17b567059d59
Revises: 88f9cf1195cb
Create Date: 2022-09-08 14:57:54.449835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b567059d59'
down_revision = '88f9cf1195cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('locale', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    op.create_index(op.f('ix_users_locale'), 'users', ['locale'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_locale'), table_name='users')
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_column('users', 'locale')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
