"""empty message

Revision ID: e06ff6dbb9d4
Revises: 17b567059d59
Create Date: 2022-09-12 16:42:32.495171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e06ff6dbb9d4'
down_revision = '17b567059d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personal_data_access', sa.Boolean(), nullable=False))
    op.drop_column('users', 'personal_data_acess')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personal_data_acess', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('users', 'personal_data_access')
    # ### end Alembic commands ###
